; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
board_build.partitions = partitions/4mb_spiffs.csv
board_build.flash_size = 4MB
board_build.flash_mode = qio
; change microcontroller
board_build.mcu = esp32
framework = arduino
monitor_speed = 115200

build_src_filter = +<*.h> +<carWithCamera/*.h> +<carWithCamera/main.cpp>
lib_deps = 
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
	cytrontechnologies/Cytron Motor Drivers Library@^1.0.1
	madhephaestus/ESP32Servo@^3.0.9
	waspinator/AccelStepper@^1.64
;; when pushing firmware, short GPIO0 and GND pin
;; if firmware upload fails, then push the boot button once

[env:nodemcu-32s-carBLE]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
build_src_filter = +<*.h> +<bleCar/*.h> +<bleCar/main.cpp>
lib_deps = 
	cytrontechnologies/Cytron Motor Drivers Library@^1.0.1
	madhephaestus/ESP32Servo@^3.0.9
	waspinator/AccelStepper@^1.64

[env:nodemcu-32s]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
build_src_filter = +<*.h> +<main.cpp>
lib_deps = 
	cytrontechnologies/Cytron Motor Drivers Library@^1.0.1
	madhephaestus/ESP32Servo@^3.0.9
	waspinator/AccelStepper@^1.64


[env:dfrobot_romeo_esp32s3]
platform = espressif32
board = dfrobot_romeo_esp32s3
framework = arduino
monitor_speed = 115200
build_src_filter = +<*.h> +<main.cpp>
lib_deps = 
	cytrontechnologies/Cytron Motor Drivers Library@^1.0.1
	madhephaestus/ESP32Servo@^3.0.9
	waspinator/AccelStepper@^1.64